### ISSUE TITLE
Mullvad VPN servers clutter network devices list and exit nodes list

### ISSUE THREAD

**Issue by masatoki-abe** [SneWs/tail-tray#76]
With the partnership between Tailscale and Mullvad VPN, users can now utilize Mullvad VPN servers as exit nodes in their Tailscale network.

tail-tray displays both the list of connected devices and available exit nodes. However, when the Mullvad VPN option is enabled, all global Mullvad VPN servers appear in these lists, which severely reduces the readability and usability of the UI.

This issue affects both the exit node selection list and the general network device list, making it hard for users to quickly locate and manage their own devices, as they are buried among hundreds of Mullvad servers displayed on the same level.

### Proposed Improvement

* Group Mullvad VPN servers by continent and country, and make the groups collapsible

  Example:

  * ▶ Europe
    * Germany
    * Sweden
    * ......
  * ▶ North America
    * United States
    * Canada
    * ......
  * ▶ ......

Thanks for the great work on this project — looking forward to your thoughts!

| ![Image](https://github.com/user-attachments/assets/18155797-90ab-4c23-b9d4-c9f1eb6c5d73) | ![Image](https://github.com/user-attachments/assets/4c5366b2-32d7-43f4-b409-a33037372836) |
|:--:|:--:|
| **Device List** | **Exit Node List** |

**Comment by SneWs** [comment]
Howdy, well that's cool, and an utterly broken UI experience 😆 

Since I don't have a payed subscription for Tailscale nor Mullvad, I'm gonna have a hard time reproducing your experience and hence have a hard time coming up with a good fix for it.

However, if you could dump the tailscale status command in a terminal and pipe it to a text file or paste it in here I can use that as a base for how to impl a good solution for this 👍 

**In a terminal**
`tailscale status --json > ~/Desktop/dump.txt` 
and attach the dump.txt file to this issue.

**Comment by masatoki-abe** [comment]
Thanks for picking this up! Here's the `tailscale status --json` output as requested.

[dump.txt](https://github.com/user-attachments/files/20271422/dump.txt)

**Comment by SneWs** [comment]
Thank you, this helps a lot! 👍 
Just by taking a quick peek at the file it seems that all the mullvad stuff is tagged accordingly, so should be an easy fix to get this working 😄

**Comment by SneWs** [comment]
I've pushed the initial work for this to this PR https://github.com/SneWs/tail-tray/pull/78 

It would be great if you could pull down the branch and build from source and see if it works for you. 

Use branch: `feature/mullvad-exit-nodes-support`

**Instructions on how to build from source:**
https://github.com/SneWs/tail-tray/blob/master/docs/build-from-src.md

**Comment by SneWs** [comment]
@masatoki-abe Let me know if you need assistance in trying this out by building locally. If it's easier for you to just get a deb file I can give it a go and produce a branch specific deb file for you otherwise. 

Thanks

**Comment by masatoki-abe** [comment]
Thanks and sorry for the delayed response!

I built the `feature/mullvad-exit-nodes-support` branch locally and tested it. I really appreciate the effort — however, I found two issues:

1. **Mullvad exit node grouping doesn’t seem to be working.**  
   Not sure why — all servers still appear in a flat list in the GUI.

2. **Changing the exit node from the GUI fails.**  
   From what I can tell in the logs, this seems to be due to the command using the hostname *without* the full domain. Here’s a snippet from the log:

```
"invalid value \"ca-van-wg-302\" for --exit-node; must be IP or unique node name\n"
```

And here’s the full log output:

```
masatoki@he-arch ~ [255]> tail-tray
Will use locale:  "ja_JP" for application
Using TRANSLATION_DIR from cmake compile definition!
Translation dir:  "/usr/local/tail-tray"
Failed to load translations from all known locations
Unknown property overflow-y
Unknown property overflow-y
Unknown property overflow-y
Tailscale seems to be installed, let's bootstrap and run!
qt.core.qobject.connect: QObject::connect: signal not found in QProcess
Process exit code  0  -  QProcess::NormalExit
Process exit code  0  -  QProcess::NormalExit
Process exit code  0  -  QProcess::NormalExit
Process exit code  0  -  QProcess::NormalExit
Process exit code  0  -  QProcess::NormalExit
QProcess: Destroyed while process ("tailscale") is still running.
"invalid value \"ca-van-wg-302\" for --exit-node; must be IP or unique node name\n"
Command "SetExitNode" recv. std error
Process exit code  1  -  QProcess::NormalExit
```

Let me know if you'd like more detailed logs or if there's anything I can help test further!

**Comment by SneWs** [comment]
Thank you. I'll add a bunch of logging around this and you can re-build and re-run and we should be able to get to the bottom om this :) 

When I run the tests locally using your dump file everything is passing as expected:
![Image](https://github.com/user-attachments/assets/fa58862e-8c39-44ca-800a-f6f5f034cbae)

Please do a pull and build and paste the output from your terminal and see what output we get from running on your machine. Thank you.

**Comment by SneWs** [comment]
And I think I found the issue, it's not in the parsing of the data, but rather a brain fart in the menu manager and how it organizes mullvad and non-mullvad devices...

Sync latest and give it a go and see what happens 👍

**Comment by masatoki-abe** [comment]
I tested the latest version and both the grouping of exit nodes and setting them via the GUI are working perfectly now.

If possible, one small improvement I'd love to see: sorting the exit nodes (and countries) alphabetically within the groups. That would make it even easier to navigate the list.

Really appreciate your fast response and support on this — thanks again!

**Comment by masatoki-abe** [comment]
Thanks again for the update!

I’ve tested the latest version and can confirm the following:

- Grouping by country is now working correctly.
- Sorting of countries within the list is also working great.
- Setting an exit node from the GUI works perfectly now.

However, I noticed that the exit nodes themselves are not sorted within each country group — they still appear in what looks like a random order.

Also, in some cases I’m seeing blank checkboxes in the exit node list. Based on the output of `tailscale exit-node list --filter=Germany`, it seems that the hostname field is empty for some nodes, which could explain this.  
So this part might be a limitation or quirk on the Tailscale CLI side rather than in tail-tray.

Let me know if you'd like me to gather more details or test any specific cases. Thanks again for your work on this!

| ![Image](https://github.com/user-attachments/assets/eae9d969-9bff-4f14-965b-bd7fc09f3022) | ![Image](https://github.com/user-attachments/assets/479de033-bd1f-4ef1-b7f1-2ef7f17efbed) |
|:--:|:--:|
| Exit Node List | Tailscale CLI Output |

**Comment by SneWs** [comment]
Any chance you've tested latest changes @masatoki-abe ?

**Comment by masatoki-abe** [comment]
Sorry for the late reply — I’ve just had a chance to test the latest changes.

I really like how the exit nodes are now grouped by city — it makes the list much easier to browse, great work!

That said, it still looks like the sorting of exit nodes within each group isn’t working yet — the nodes appear to be in a random order rather than sorted by name.

Let me know if there’s anything else you’d like me to check or test further. Thanks again for all your continued efforts!

![Image](https://github.com/user-attachments/assets/2c80f07f-a89d-4b83-ad42-416515c9f72b)

**Comment by SneWs** [comment]
Thank you for the continued feedback, you are quite correct. I have now made sure that the nodes also are lexicographically sorted when grouped by countr/city/node using the dns name.

Give it a go, I think this will be the final commit now and will be merging this into mainline.
